### ISSUE TITLE
running error of Searchlight with Anaconda3 and ICC

### ISSUE THREAD

**Issue by yidawang** [brainiak/brainiak#152]
Using Anaconda3 and ICC to run the Searchlight example in `examples/searchlight` as `mpirun -np 1 python example_searchlight.py`, I received the following error:
```ImportError: /path/to/anaconda3/lib/python3.5/site-packages/_multiprocess.cpython-35m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strcpy```

This error doesn't appear on my Macbook Pro with Anaconda3 and clang.

**Comment by yidawang** [comment]
It is an issue about `multiprocess`, which can be fixed by reinstalling it via `pip install -v --global-option=build_ext --global-option="-lirc" --global-option="-lintlc" multiprocess` if you are using ICC/ICPC as the default C/C++ compiler

**Comment by mihaic** [comment]
Is there no way to set those library options independently of Python, so that they are in effect when installing Multiprocess?

**Comment by mihaic** [comment]
Have you had the change to look at setting the options? One way to deal with the issue and others that may arise with ICC is to create a Q&A document.

**Comment by mihaic** [comment]
Closing because it is not specific to BrainIAK.
