### ISSUE TITLE
utils: center_mass_exp has no tests

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#254]

**Comment by QihongL** [comment]
Hi, I am learning about Brainiak. I might be able to contribute every once in awhile, so I am interested in solving this issue to get familiarized with the process. 

I am slightly confused about the way `center_mass_exp ` deals with negative `a` and/or `b`. For example, when `a` and `b` to be negative, exponential should have zero mass. I thought this function should return `(a+b)/2`, or simply return some warning. Currently, `center_mass_exp(-2,-1) = -1.58197670687`. Am I misunderstanding something?

**Comment by mihaic** [comment]
Hello, @QihongL! Thank you for your interest in BrainIAK. Any contribution is appreciated.

@lcnature, could you please chime in?

**Comment by lcnature** [comment]
@QihongL 
Thanks for pointing this out! I forgot to consider the case. 
So I think if b is smaller or equal than zero, then an error should be thrown out.
If a is smaller than 0 but b is not, then this seems fine, we can set a to 0 and do the same calculation as before.

**Comment by QihongL** [comment]
Ah, I thought you wouldn't allow `a<0`. I see... Still, if `a < 0`, it might suggest the user doesn't know what this function is trying to do. I guess it makes sense to at least throw a warning in this case? For example, the warning message can remind the user to simply set `a = 0`.

**Comment by lcnature** [comment]
@QihongL Good point! In that case, maybe we should just enforce a>=0 and throw an error if not.

**Comment by lcnature** [comment]
fixed!
