### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#272]
This will make it easier for users to experiment with BrainIAK.

The image used at the Methods in Neuroscience at Dartmouth summer school looks like a good starting point:
https://github.com/Summer-MIND/mind-tools/blob/master/Dockerfile

**Comment by yidawang** [comment]
I agree that this is a good way to relieve the installation pain. However, what about the multi-node usage of BrainIAK?

**Comment by mihaic** [comment]
The use case for Docker is experimenting with BrainIAK as a new user, not running BrainIAK on a regular basis. Therefore, I think it is fine to not offer multi-node support.

**Comment by mihaic** [comment]
I uploaded a handcrafted image on Friday:
https://hub.docker.com/r/brainiak/brainiak/

I am re-purposing this issue for adding a Dockerfile for building the image consistently.
