### ISSUE TITLE
add a simplified route to installation

### ISSUE THREAD

**Issue by jeremymanning** [brainiak/brainiak#278]
I'd like to be able to install brainiak using `pip install brainiak`.  However, there are several additional steps required (that seem in practice to fail often on unclean systems, and sometimes even on clean ones).  For example on Macs, my understanding is that homebrew, xcode, llvm, cmake, and mpich are all needed to compile the optimized C++ parts of the toolbox (e.g. system-specific binaries are needed).

However, it would be nice if `pip install brainiak` "just worked," in the sense that perhaps the code could revert to a slower non-C++ version (e.g. in the absence of support for compiling custom binaries, and/or if compilation fails for any reason).  Everything would run more slowly, but that seems better than not running at all!

**Comment by mihaic** [comment]
I agree with the need to simplify installation. We are working on it.

In fact, we have already decided to offer Python wheels, which I think will help (see issue #286, which I should have opened a couple of weeks ago).

Meantime, consider our Docker image:
https://github.com/brainiak/brainiak#docker

**Comment by danielsuo** [comment]
What's the status on Python wheels? I can help!

**Comment by danielsuo** [comment]
FYI: work in progress in pull request #314

**Comment by mihaic** [comment]
Unfortunately, the effort to provide Python wheels (issue #286) is blocked by the lack of MPI4PY wheels.

Because we introduced an alternative simple installation solution (Conda packages), I am closing this issue. The conversation about wheels continues in issue #286.
