### ISSUE TITLE
Install issue on Mac OS X 10.12.6

### ISSUE THREAD

**Issue by manojneuro** [brainiak/brainiak#285]
Hi,

I tried installing BrainIAK on a new Mac. It did not finish with "Successfully Installed". I am attaching the log for your reference.
[biak_nstall_fail.txt](https://github.com/brainiak/brainiak/files/1428855/biak_nstall_fail.txt)

Thanks,
Manoj

**Comment by mihaic** [comment]
Hello, Manoj!

It looks like you are using a combination of Brew and Conda packages. I think it would be best to try one or the other, not a combination. I suggest you try Brew, since we already provide step-by-step instructions in the BrainIAK README. In case you actually installed Python from Brew and intended to use that for the BrainIAK installation, I suggest you use change your `PATH` so Brew is first or use the full path when calling `python3`, i.e.:
```
/usr/local/bin/python3 -m pip install -U brainiak
```

**Comment by manojneuro** [comment]
Okay thanks. I'll give this a shot. 

I had used Anaconda for using Jupyter notebooks, so maybe thats why the mixup.

**Comment by manojneuro** [comment]
Hi Mihai,

I got one additional error (something about TFA, see below) but the end status said, "Successful Install". Is this good?

Install Log:
=============================================
 **brainiak/factoranalysis/tfa_extension.cpp:24:10: fatal error: 'pybind11/pybind11.h' file not found
  #include <pybind11/pybind11.h>**
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command '/usr/local/opt/llvm/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for brainiak
  Running setup.py clean for brainiak
  Running setup.py bdist_wheel for nitime ... done
  Stored in directory: /Users/manojkumar/Library/Caches/pip/wheels/05/0f/4b/63bba7a487d3cfb165c7ec095fe0d9135e8ba5a126ce25b0e2
Successfully built nitime
Failed to build brainiak
Installing collected packages: cython, mpi4py, numpy, six, python-dateutil, pytz, cycler, pyparsing, matplotlib, scipy, nitime, scikit-learn, pymanopt, theano, pybind11, nibabel, typing, brainiak
  Running setup.py install for brainiak ... done
Successfully installed brainiak-0.5 cycler-0.10.0 cython-0.27.2 matplotlib-2.1.0 mpi4py-2.0.0 nibabel-2.2.0 nitime-0.7 numpy-1.13.3 pybind11-2.2.1 pymanopt-0.2.3 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.3 scikit-learn-0.19.1 scipy-1.0.0 six-1.11.0 theano-0.9.0 typing-3.6.2

========================================

**Comment by mihaic** [comment]
Yes, the installation was successful. Closing the issue.
