### ISSUE TITLE
dtype in EventSeg Cython should be float

### ISSUE THREAD

**Issue by danielsuo** [brainiak/brainiak#289]
Code [here](https://github.com/brainiak/brainiak/blob/master/brainiak/eventseg/_utils.pyx) will fail on the following example

```python
masked_log(np.array([0, 1, 2]))
```

We get the following error:

```
y[i] = float('-inf')
OverflowError: cannot convert float infinity to integer
```

**Comment by danielsuo** [comment]
Fix could be simple, but I'm not aware of the full range of datatypes that masked_log should accept or what the casting behavior should be.

**Comment by danielsuo** [comment]
@cbaldassano

**Comment by cbaldassano** [comment]
I believe that the current code only needs masked_log to support floats (it is called from the _log function), so Daniel's suggested fix of just changing the datatype explicitly to float should be fine.
