### ISSUE TITLE
Add "Need Help" button as a top link on the Home Page

### ISSUE THREAD

**Issue by manojneuro** [brainiak/brainiak#311]
Hi,

Currently the "Need Help" button is embedded towards the bottom of the brainiak Home page. It would make it easier for users to know where to log issues etc. to see the link on top.

Thanks,
Manoj

**Comment by mihaic** [comment]
Please open an issue at https://github.com/brainiak/brainiak.github.io and close this one.

**Comment by manojneuro** [comment]
Transferring issue to brainiak website list.
