### ISSUE TITLE
Why does setup.py fail?

### ISSUE THREAD

**Issue by danielsuo** [brainiak/brainiak#315]
For testing the ```mpi4py``` wheels, we try installing from source four different ways:

1. ```pip install .```
2. ```pip install -e .```
3. ```python setup.py develop```
4. ```python setup.py install```

The first two succeed, but the last two fail (even if mpi4py is installed from source with the appropriate dependencies installed). Not going to look into it now, but wanted to record the issue.

**Comment by mihaic** [comment]
Although it may seem obvious (1, 2) should behave the same as (3, 4), they are different. As far as I know, we do not use 3 and 4. If we need to use them, please reopen.
