### ISSUE TITLE
FCMA example code

### ISSUE THREAD

**Issue by jhutchin** [brainiak/brainiak#317]
example code for FCMA, `classification.py` throws errors on: `from brainiak.io import dataset`
i.e.: https://github.com/brainiak/brainiak/blob/master/examples/fcma/classification.py#L17

but is fixed by, e.g.,: `from brainiak import io as dataset`
(my code is not ready for a pull request, otherwise I'd flag it that way...)

**Comment by yidawang** [comment]
I am aware of it. I can take care of this later but if anyone else would like to fix it (and perhaps similar issues in other example code files), please feel free to go ahead.

**Comment by yidawang** [comment]
fixed by #322
