### ISSUE TITLE
docs: Warn against running `python setup.py`

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#318]
It is not the same as `pip install`, as pointed out in issue #315. We should warn users in the documentation.

**Comment by sameshl** [comment]
@mihaic I would like to work on this. Is it fine to add a warning at the end of [quickstart guide](https://brainiak.org/docs/#quickstart)?

**Comment by mihaic** [comment]
@sameshl, thanks for the offer. I think it is best to keep the quickstart guide short as simple; the installation guide is a more appropriate place:
https://brainiak.org/docs/installation.html

**Comment by sameshl** [comment]
@mihaic I see. Will make the required change
