### ISSUE TITLE
Conda install information missing on brainiak home

### ISSUE THREAD

**Issue by manojneuro** [brainiak/brainiak#362]
On the brainiak homepage http://brainiak.org, instructions for conda install have not been added under "Getting Started".

**Comment by mihaic** [comment]
@manojneuro?

**Comment by danielsuo** [comment]
@manojneuro filed here
https://github.com/brainiak/brainiak.github.io/issues/22

I requested the instructions they had given to students (battle-tested and
all) in the Yale course.

**Comment by mihaic** [comment]
Thanks, @danielsuo. Closing this issue.
