### ISSUE TITLE
io: Add list example for load_images_from_dir

### ISSUE THREAD

**Issue by sharifkronemer** [brainiak/brainiak#369]
Each time MaskedMultiSubjectData is called it requires the images of interest to be loaded and masked, otherwise a "StopIteration:" error appears, even if the images have been previously loaded. A helpful optimization would be to allow images to be loaded (load_images) and masked once initially and then to be able to call MaskedMultiSubjectData multiple times thereafter without having to reload/re-mask the images for each call of MaskedMultiSubjectData. A possibility is to update the load_images function so that the object created can be operated on more than once.

**Comment by mihaic** [comment]
@sharifkronemer?

**Comment by sharifkronemer** [comment]
I appreciate the follow-up! I implemented your suggestion above and it worked well. Thank you!

**Comment by mihaic** [comment]
Happy to help.

I am re-purposing this issue into a documentation issue: the docstring should mention the example I gave.

**Comment by sameshl** [comment]
I would like to fix this but I am having a lot of trouble installing brainiak due to requirement errors. 
So, can you show the output of 
> ```
> images = list(io.load_images_from_dir("face_scene", "bet.nii.gz"))
> ```

so I can include it in docstring as doctest

**Comment by mihaic** [comment]
@sameshl, I think it is enough to mention the `list` call in the docstring without output. Doctests could be helpful, be we don't use them at the moment.
