### ISSUE TITLE
Add transform_subject functionality SRM

### ISSUE THREAD

**Issue by CameronTEllis** [brainiak/brainiak#370]
RSRM has the functionality to learn the weights for a new subject while keeping the shared response fixed (.transform_subject: https://github.com/brainiak/brainiak/blob/a16df0070b571cf5583af4c39331f3b59192a709/brainiak/funcalign/rsrm.py#L221). This would be great to have with SRM and all other SRM functions moving forward

**Comment by mihaic** [comment]
@CameronTEllis, shouldn't this be open until PR #371 is merged?
