### ISSUE TITLE
extra step for installing brainiak for brew version of python

### ISSUE THREAD

**Issue by jeremymanning** [brainiak/brainiak#374]
I was able to get brianiak installed with the homebrew version of Python (on MacOS High Sierra), but I had to call `brew install pybind11` (in addition to the installation instructions posted in the documentation) in order to get the installation to complete.

**Comment by mihaic** [comment]
What error do you see if you do not run the extra Brew command?

**Comment by mihaic** [comment]
Closing for lack of information. Feel free to reopen if still an issue.
