### ISSUE TITLE
brainiak run in miniconda on Windows?

### ISSUE THREAD

**Issue by jaetzel** [brainiak/brainiak#383]
Will brainiak run on Windows within miniconda? The "Win" link in Method 1 Step 1 on http://brainiak.org/#get-started makes me think it does, but elsewhere the documentation states that windows is not supported. (I tried the installation and got a PackagesNotFoundError.)

Thanks!

**Comment by lcnature** [comment]
@mihaic Indeed I got the same error when trying on Windows. Shall we consider changing the website? Is the channel specific to certain OS?

**Comment by mihaic** [comment]
@jaetzel, this is an error in our documentation. Thanks for bringing it up. We do not provide Conda packages for Windows.
