### ISSUE TITLE
utils: Document difference between compute_p_from_null_distribution and p_from_null

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#397]
See:
https://github.com/brainiak/brainiak/pull/384#issuecomment-438000981

**Comment by snastase** [comment]
As far as I can tell `p_from_null` was performing a specific function that was only used in the old `isfc` function, and is no longer referenced anywhere in `brainiak`. In this case, I think `compute_p_from_null_distribution` supersedes `p_from_null`, and `p_from_null` can be removed. However, I may shorten the name of `compute_p_from_null_distribution` as I only named it this to not overlap with the pre-existing `p_from_null`.

**Comment by mihaic** [comment]
That makes sense. Please remember to include a news item about the removal of `p_from_null` (see point 7 http://brainiak.org/docs/contributing.html#how-to-contribute). Looking forward to the PR!

**Comment by snastase** [comment]
Replaced old `p_from_null` with newer functionality from `compute_p_from_null_distribution` in #405 (commit [daa5d41](https://github.com/brainiak/brainiak/pull/405/commits/daa5d4190db01ebd7d4340774705b1bb6fb5eca6)). Note that the new functionality now uses the older simpler function name. This also required removing the `ecdf` functionality which is no longer used anywhere in BrainIAK (commit [aa0c37d](https://github.com/brainiak/brainiak/pull/405/commits/aa0c37d11bc5b3602caee33dde6eb45755177c83).
