### ISSUE TITLE
Release schedule for v0.9.2 ?

### ISSUE THREAD

**Issue by emdupre** [brainiak/brainiak#452]
Thanks for making this great tool !

I was wondering if you had an anticipated schedule for the next release (looks like v0.9.2, or perhaps v1.0.0 ?!). In particular, I'd like to access the new fastSRM implementation. 

For now, I'll plan to just build from GitHub's source, but since there hasn't been in a release in 5 or so months I was wondering if you had any anticipated timeline, here.

Thanks again,

Elizabeth

**Comment by mihaic** [comment]
Hello, @emdupre! We will release the next version as soon as we sort out the infrastructure issues that are preventing our tests from passing. Hopefully by the end of next week.

**Comment by mihaic** [comment]
Quick update: we fixed or worked around all the issues causing the tests to fail, except one related to MPI in the Conda package on Linux. We are working on it, but likely will need a few more days to get the release ready.

**Comment by emdupre** [comment]
Thanks for the update, @mihaic ! Very much appreciated :smile_cat:

**Comment by mihaic** [comment]
We released a new version. Thank you for your patience.
