### ISSUE TITLE
utils.py: undocumented assumptions in function p_from_null for the two-sided case

### ISSUE THREAD

**Issue by me-sh** [brainiak/brainiak#456]
Function p_from_null: When side == 'two-sided', the p-value calculation seems to assume that the null distribution is 1) symmetrical and 2) centered around zero. Violation of these assumptions leads to inaccurate results. A link to the relevant line is below. 
[https://github.com/brainiak/brainiak/blob/dc12929a99529a69da3c3242e9c9fd31c308fbb0/brainiak/utils/utils.py#L853
](url)

**Comment by mihaic** [comment]
@snastase, could you please weigh in?

**Comment by me-sh** [comment]
can't replicate the bug, not sure there's a problem anymore
