### ISSUE TITLE
Grey matter mask MNI too big?

### ISSUE THREAD

**Issue by stephanwu89** [brainiak/brainiak#468]
Hi all,

I used the command
mask, template = sim.mask_brain(dimensions, mask_self=False)
to generate a grey matter mask. But it seems to be that this mask also includes part of the white matter. Could that be true? How could I apply more strict criterias to keep white matter away in that mask?

<img width="519" alt="Bildschirmfoto 2020-06-20 um 13 22 01" src="https://user-images.githubusercontent.com/43010731/85200593-0e048700-b2f9-11ea-98b1-1275b8986661.png">

Best,
Stephan

**Comment by CameronTEllis** [comment]
Hi Stephan,

Yes the mask that is being generated is based on the tissue priors from FSL and so will include some white matter. The output of your function produces two volumes, the first of which is what you plotted and shows the binarized volume, based on assumptions that the brain voxels and non brain voxels live in two different distributions of voxel intensity. If you don't think that threshold is appropriate, you can manually recreate the mask by taking the second output (`template`) and thresholding that at whatever you like (e.g. `mask = template > 0.5`). In this case the values are interpretable: they are the proportion likelihood that a given voxel is grey matter.

**Comment by stephanwu89** [comment]
Hi Cameron,
Thanks a lot!
Is it also possible to generate a mask/template for MNI, supratentorial only with grey matter and basal ganglia?

Best,
Stephan

**Comment by CameronTEllis** [comment]
Do you mean you want to simulate realistic fMRI data but only in those regions, or do you mean you want to simulate whole brain data and insert signal in those regions? Because of how the code estimates things like smoothness, creating a volume that is only a small ROI may produce inaccurate data. However, you could easily make the data whole brain and then mask it afterwards to the regions you care about.

**Comment by stephanwu89** [comment]
I mean simulating only the voxels in those regions. So all the voxels in those regions where I am interested in should be 1 and the other 0.

**Comment by CameronTEllis** [comment]
You certainly could just simulate voxels in that region. In that case you would need a mask with binary values indicating which voxels are in and out of the ROI. You also need a template, defining the mean activity in the region you expect. However, I am not sure about the accuracy of doing this kind of `small volume` simulation, it is more appropriate to simulate the whole brain and mask down to the region of interest.

**Comment by stephanwu89** [comment]
Yes thats for sure. But my problem is, I dont know how to generate such a mask. A mask only containing supratentorial parts.
Best

**Comment by CameronTEllis** [comment]
To create masks you could use data that has been previously collected, either by you or someone else. Meta-analysis tools like neurosynth may help. You could also just manually trace the mask in a tool like FSLeyes.

**Comment by CameronTEllis** [comment]
If you have any other questions, feel free to reach out, either via email or gitter. I will close the issue now
