### ISSUE TITLE
funcalign: Add RSRM compatibility with scikit-learn >=0.24

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#491]
Starting with version 0.24, scikit-learn enforces the requirement to set parameters passed to estimators as instance attributes:
> Fix base.BaseEstimator.get_params now will raise an AttributeError if a parameter cannot be retrieved as an instance attribute.
https://scikit-learn.org/stable/whats_new/v0.24.html#sklearn-base

RSRM has a `gamma` parameter, but it does not set a `gamma` attribute; instead it stores the value in the `lam` attribute:
https://github.com/brainiak/brainiak/blob/master/brainiak/funcalign/rsrm.py#L111

The resulting error shows up in our tests:
https://travis-ci.org/github/brainiak/brainiak/jobs/759097966#L866

Should we rename `lam` to `gamma`?

**Comment by TuKo** [comment]
Yes, renaming it should be fine. Just created a PR
