### ISSUE TITLE
install: PackageNotFoundError

### ISSUE THREAD

**Issue by GMerakis** [brainiak/brainiak#496]
When trying to install via anaconda, I get the following error:
DOC: https://brainiak.org/docs/installation.html

`conda install -c brainiak -c defaults -c conda-forge brainiak
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - brainiak

Current channels:

  - https://conda.anaconda.org/brainiak/win-64
  - https://conda.anaconda.org/brainiak/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

**Comment by GMerakis** [comment]
channels have already been added.
not quite sure why...

**Comment by GMerakis** [comment]
using pip throws error ....

>pip install brainiak
Collecting brainiak
  Using cached brainiak-0.11.tar.gz (6.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
...
      return hook(config_settings)
    File "C:\Users\yukik\AppData\Local\Temp\pip-build-env-uzorphfj\overlay\Lib\site-packages\setuptools\build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\yukik\AppData\Local\Temp\pip-build-env-uzorphfj\overlay\Lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "C:\Users\yukik\AppData\Local\Temp\pip-build-env-uzorphfj\overlay\Lib\site-packages\setuptools\build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\yukik\AppData\Local\Temp\pip-build-env-uzorphfj\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 72, in <module>
      class BuildExt(build_ext):
    File "setup.py", line 81, in BuildExt
      or 'icc' in sysconfig.get_config_var('CC')):
  TypeError: argument of type 'NoneType' is not iterable
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/59/9a/c60a06af9d04270b94e6440855a230efda66fab6fe9ae203402b90639b68/brainiak-0.11.tar.gz#sha256=0d5ce0d9f2eeced5638b74cbbc97df62bce40ca6098cd71b40f75fa4407cd947 (from https://pypi.org/simple/brainiak/) (requires-python:>=3.5). Command errored out with exit status 1: 'E:\DataScience\Anaconda\python.exe' 'E:\DataScience\Anaconda\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\yukik\AppData\Local\Temp\tmp4gdn2bry' Check the logs for full command output.

**Comment by GMerakis** [comment]
After creating new env this still does not work...

**Comment by mihaic** [comment]
Hello, @GMerakis! Unfortunately, we do not support Windows. That is why there is no Conda package for Windows. We certainly welcome contributions that add Windows support.
