### ISSUE TITLE
Feature: Enable Windows support

### ISSUE THREAD

**Issue by DasDominus** [brainiak/brainiak#498]
Right now there are some issues when trying to install the package on windows.
This issues tracks the effort to remove the blockers on windows support

**Comment by DasDominus** [comment]
So after some playing around, what I did:
- clone the repo
- in root of repo, run $pip install -e .

This resulted in the following issues:
1. factoranalysis and fcma does not compile
This is likely due to the default compiler on Windows (I have VS 2019 installed) is MSVC and does not recognize the --std=c++14 flag

I actually ran into the same issue when trying to install on linux (which had gcc/g++ installed)

might need to dig around to figure out the compiling story here.

Other than this other module seems  to work ATM. I'll check the tutorials to see if anything else does not work.

**Comment by mihaic** [comment]
Thanks, @DasDominus. This helps.

**Comment by mihaic** [comment]
Fixed by PR #549.
