### ISSUE TITLE
``StopIteration`` error in `from_masked_images` method

### ISSUE THREAD

**Issue by sangfrois** [brainiak/brainiak#513]
I am reaching out to you because I cannot figure by myself a solution for this error.

My code looks like this : 
```
 for task in glob.glob(f"{postproc_path}/*/"):
        task = task[-12:]
        logger.info(f'Importing data')
        files = sorted(glob.glob(f'{postproc_path}/{task}/*.nii.gz*'))

        images = load_img(files)
        logger.info("Loaded files")
        masked_imgs = image.mask_images(images, brain_mask)
        logger.info("Masked images")

        # compute ISC
        bold_imgs = image.MaskedMultiSubjectData.from_masked_images(
                masked_imgs, len(files))
```
Where : images are loaded ``nii`` post processed files using ``nilearn.images``  (tried it with ``brainiak.io`` module as well)

Seems to me that a generator object is passed to the method and turned into an iterator. The code [breaks here](https://github.com/brainiak/brainiak/blob/ee093597c6c11597b0a59e95b48d2118e40394a5/brainiak/image.py#L64). 

Yet, I'm applying cell 5 from [your tutorial](https://brainiak.org/tutorials/10-isc/). I wonder why it's not working with my data. 

It may be my postprocessed files that are corrupted, but less probable than anything else as they are correctly loaded. I may be mistaken. 

Being from a psychology background, there's a limit to my pythonic fluency and I would appreciate some help from the community.

Any troubleshooting insights for me ?

Thank you very much

**Comment by mihaic** [comment]
Hello, @sangfrois. I am sorry to hear about your issue.

Could you add `print(len(images))` before calling `from_masked_images` and share the output?

Did you run the ISC tutorial successfully?

**Comment by sangfrois** [comment]
Hello @mihaic !

Thank you so much for your fast response. I did run it successfully!

i get : 
``TypeError: object of type 'generator' has no len()`` 

Does that mean I plainly did not correctly postprocess my EPI files ?

**Comment by mihaic** [comment]
Not necessarily. How about `len(files)`? What is `load_img`? Are you executing exactly the code in the issues or are there maybe other lines you skipped?

**Comment by sangfrois** [comment]
as I said in the description : ``load_img`` is a utility to load ``.nii.gz`` files from the ``nilearn.image`` module. 

``files`` is a list returned by ``glob.glob(path/to/files.nii.gz`` so ``len(files)`` is 6. I load data from 6 subjects.

**Comment by mihaic** [comment]
Try `images = list(load_img(files))`. If that doesn't work, please paste `load_img` here.

**Comment by sangfrois** [comment]
OH WOW! @mihaic 

I'm sorry, I went ahead of myself, being sure i was listing files correctly, but I think it's the source of my error. I tried it in a interactive shell, and it spitted out empty lists. 

```
brain_mask = load_mni152_template()
coords = np.where(brain_mask)
brain_nii = load_img(brain_mask)
print("Loaded mask")


@click.command()
@click.argument('postproc_path', type=click.Path(exists=True))
@click.argument('isc_map_path', type=click.Path(exists=True))
def map_isc(postproc_path, isc_map_path, pairwise=False):
    """
    Compute ISC for brain data.

    note
    """
    # specify data path (leads to subdi
    logger = logging.getLogger(__name__)
    logger.info('Starting Temporal ISC workflow')
    tasks = glob.glob(f"{postproc_path}/*/")
    # walks subdirs with taks name (task-s01e01a)
    for task in sorted(tasks):
        # HERE : the string returned is incorrect so it's looking for unexisting paths
        task = task[-12:]
        logger.info(f'Importing data')
        files = sorted(glob.glob(f'{postproc_path}/{task}/*.nii.gz*'))

        images = io.load_images(files)
        logger.info("Loaded files")
        masked_imgs = image.mask_images(images, brain_mask)
        logger.info("Masked images")

        # compute ISC
        bold_imgs = image.MaskedMultiSubjectData.from_masked_images(
                masked_imgs, len(files))
````
It seems to load files correctly and I don't get the StopIteration again.

Now, i get an ValueError because the mask I import does not have the same shape. 

I feel so stupid! Sorry for mobilizing your energy for such an error on my part.

Thank you so much. I think we can close this now.

**Comment by mihaic** [comment]
You're welcome. :)
