### ISSUE TITLE
Can BrainIAK be used for analysis of Functional Near Infrared Spectroscopy (FNIRS)??

### ISSUE THREAD

**Issue by cosmosanalytics** [brainiak/brainiak#514]
Can BrainIAK be used for analysis of Functional Near Infrared Spectroscopy (FNIRS)??

**Comment by mihaic** [comment]
Hello, @cosmosanalytics. Our methods use fMRI data, but maybe some could be ported to other data types. Please have a look at the tutorials and see if can apply to your data:
https://brainiak.org/tutorials
