### ISSUE TITLE
Statsmodel reference to import AMRA module is outdated in fmrisim

### ISSUE THREAD

**Issue by soukhind2** [brainiak/brainiak#520]
The package name has changed since statsmodels is now in its 0.13 version. Instead of 
from statsmodels.tsa.arima_model import ARMA
the code should be changed to the newer library. Currently, the noise generation is not working.

**Comment by davidt0x** [comment]
This has been fixed (updated to new API) in https://github.com/brainiak/brainiak/pull/511. Waiting on some further issues to be fixed before merge but feel free to use it now.

**Comment by soukhind2** [comment]
Thank you! I changed the lines on my local copy.
