### ISSUE TITLE
Some functions have deprecated due to packages update.

### ISSUE THREAD

**Issue by Chen1997237** [brainiak/brainiak#530]
Hi, when I use BrainIAKto to load some data, I got some error:

```
get_data() is deprecated in favor of get_fdata(), which has a more predictable return type. To obtain get_data() behavior going forward, use numpy.asanyarray(img.dataobj). * deprecated from version: 3.0 * Raises as of version: 5.0

```

It seems like due to some nibabel function's usage has changed, but the built in functions of BrainIAK did not. Would you mind to update the built in functions of BrainIAK in order to reduce error?

**Comment by mihaic** [comment]
Hello, @Chen1997237. Thanks for pointing out the issue. We are working on fixing it (and other issues in PR #511):
https://github.com/brainiak/brainiak/pull/511/files#diff-b16e2d322d8208bf4fc15711cd8cea00dd2c65a714f5632a9cf64a520e21b747R127
