### ISSUE TITLE
Do not attempt to upload wheel to PyPI

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#537]
We are not building wheels (https://github.com/brainiak/brainiak/issues/286). Furthermore, it is causing the publishing job to fail:
> ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Binary wheel 'brainiak-0.0.0-cp312-cp312-linux_x86_64.whl' has an      
         unsupported platform tag 'linux_x86_64'.

https://github.com/brainiak/brainiak/actions/runs/7011666442/job/19076302331

**Comment by davidt0x** [comment]
Yeah ok, I thought the wheel wouldn't hurt things. The action I am using builds the sdist and the wheel and I don't seem to be able to disable it. I will modify the action script and include it in our repo then.

**Comment by mihaic** [comment]
Now we are building wheels so we will upload them.
