### ISSUE TITLE
PyPI upload failure

### ISSUE THREAD

**Issue by davidt0x** [brainiak/brainiak#553]
Not sure what is causing this error to upload the package. I know that they recently changed things to support attestations, maybe we need to implement that to get it working?

https://github.com/brainiak/brainiak/actions/runs/11875573414/job/33094720463

**Comment by davidt0x** [comment]
Any chance that we need to do this on the brainiak pypi account:

[https://docs.pypi.org/trusted-publishers/adding-a-publisher/](https://docs.pypi.org/trusted-publishers/adding-a-publisher/)

**Comment by mihaic** [comment]
It was the indeed a PyPI publisher issue, thanks for spotting it.
